### ISSUE TITLE
Problem with NonNuProjProjectTargetPath and Project Net4.0 with Microsoft.Async Nuget

### ISSUE THREAD

**Issue by bhugot** [terrajobst/nuproj#83]
Hello I have a problem with building .Nuproj in VS when I have a referenced project in Framework .Net4.0 and using Microsoft.Async

It's failing for this Property

<_NonNuProjProjectTargetPath>$([System.IO.Path]::GetDirectoryName($(_NonNuProjProjectTargetPath)))\</_NonNuProjProjectTargetPath>

**Comment by petero-dk** [comment]
I have the same problem, I was able to get it compiling by changing the nuproj.target file to

```xml
<_NonNuProjProjectTargetPath>$([System.IO.Path]::GetDirectoryName($([MSBuild]::ValueOrDefault($(_NonNuProjProjectTargetPath),"")))\</_NonNuProjProjectTargetPath>
```

It does not reference the output files of my project, but it does find the neccessary dependencies and adds them to the nuspec.

Then I can manually add the .dll files to the lib folder

**Comment by PedroLamas** [comment]
I've been experiencing this same issue and managed to investigate this further!

Seems to be related to how `Microsoft.Bcl.Build` works in order to detect missing references to BCL packages: by overriding the `GetTargetPath` target, thus making NuProj fail...

Disabling this reference check for NuProj seems to fix the issue, so I've pushed #94 as a proper fix.

**Comment by PedroLamas** [comment]
I've updated my fix to ensure that it can be merged in the most current `Nuproj.targets` file.

**Comment by ravensorb** [comment]
Did this ever get merged in?

**Comment by kovalikp** [comment]
I've found a solution that does not require to pass global property to MSBuild task in #189.

**Comment by ravensorb** [comment]
Hmm, I am still having the problem then.  I am using the branch with that merge and am not able to use nuproj on my project that references the Bcl package.

Here is the nuproj file
https://github.com/ravensorb/Xamarin-Forms-Labs/blob/master/.nuget/Projects/XLabs.Web.NuSpec.nuproj

and it is working with
https://github.com/ravensorb/Xamarin-Forms-Labs/tree/master/src/Web/XLabs.Web

**Comment by kovalikp** [comment]
I will need to create more complex scenario for unit test. In meanwhile, could you try `https://ci.appveyor.com/project/kovalikp/nuproj/build/1.0.66/artifacts`?
